### ISSUE TITLE
about the models folder

### ISSUE THREAD

**Issue by GELIELEO** [StanfordVL/GibsonEnvV2#14]
it seems that this repo lacks a models dir in assets folder, can you provide it?

**Comment by initmaks** [comment]
@GELIELEO were you able to find it?

**Comment by initmaks** [comment]
nvm, found it:
https://github.com/StanfordVL/GibsonEnvV2/blob/f1732b085b0fbccd4c423cb8d6eda6a5ece6f1f2/docs/installation.md#download-data

**Comment by fxia22** [comment]
yes, the model folder is large so you need to download it separately.
