### ISSUE TITLE
How can I enable the 3d scene graph generation

### ISSUE THREAD

**Issue by GELIELEO** [StanfordVL/GibsonEnvV2#15]
It seems that the source code does not provide the 3d graph generation function, I come here to confirm whether this repo provides this function? if does, how to achive it?   For the purpose of saving time, thank you very much!

**Comment by fxia22** [comment]
Currently it is handled by [3DSceneGraph](https://github.com/StanfordVL/3DSceneGraph) and looks like they have not released the code yet. We will keep you updated.
