### ISSUE TITLE
Unable to run mesh_renderer_gpu_example.py (or anthing related to mesh render in examples directory)

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/GibsonEnvV2#19]
I have run successfully demo.py but I have a trouble when running file mesh_renderer_gpu_example.py caused by an error in the following log. Could you please have a look at it? I have tried to run other files related to mesh but having the same error

The log in my case is:

(py3-gibson) cndm@pi:/media/cndm/New Volume/Project-2/GibsonEnvV2/examples/demo$ python mesh_renderer_gpu_example.py 
using asset: path /media/cndm/New Volume/Project-2/GibsonEnvV2/gibson2/assets dataset path: /media/cndm/New Volume/Project-2/GibsonEnvV2/gibson2/assets/dataset
pybullet build time: Dec 17 2019 12:16:21
Traceback (most recent call last):
  File "mesh_renderer_gpu_example.py", line 10, in <module>
    model_path = sys.argv[1]
IndexError: list index out of range

**Comment by fxia22** [comment]
You need to give it an obj file, for example you can render the mesh in the dataset you downloaded:
`python mesh_renderer_gpu_example.py GibsonEnvV2/gibson2/assets/dataset/Norvelt/mesh_z_up.obj`

**Comment by chaundm** [comment]
Thank you Fei Xia,

I have tried it in that way and the problem is nearly solved because it raises another issue as followings:

![image](https://user-images.githubusercontent.com/11848133/71511342-f493fc80-28cc-11ea-85f5-b306fd66c73e.png)

Could you please help me to figure out where the issue come from?

**Comment by fxia22** [comment]
You need to use your `GibsonEnvV2` directory, which is `/media/cndm/...`

**Comment by chaundm** [comment]
It works properly, thank you so much
