### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by zubair-irshad** [StanfordVL/GibsonEnvV2#5]
I could not install GibsonV2 using the installation instructions since the GitHub link provided does not exists: https://github.com/fxia22/gibsonv2

**Comment by ahmedosman** [comment]
@zubair-irshad  the readme seems to be not updated. I successfully installed and use the simulator. Just clone using the repo link https://github.com/StanfordVL/GibsonEnvV2.git  --recursive

**Comment by fxia22** [comment]
Yes, please use `git clone  https://github.com/StanfordVL/GibsonEnvV2.git --recursive`
