### ISSUE TITLE
Using Gibson scenes in the simulators 

### ISSUE THREAD

**Issue by ahmedosman** [StanfordVL/GibsonEnvV2#8]
Hi, 

Thanks for building this simulator, its a great service for the community. 
I download the Gibson (full dataset), however the scenes are missing the floor.txt file, which result in the examples/demo.py throwing an error. Even when changing the code to ignore the scene floor map, the rendered scene is grayscale meshes. 

Is it the case Ohopee is the only scene supported now? 

Thanks,
AO

**Comment by fxia22** [comment]
We will release the meshes for gibsonv2 soon.
